### ISSUE TITLE
LCM Logger Test Hangs In WSL

### ISSUE THREAD

**Issue by alvinsunyixiao** [illini-robomaster/iRM_Autonomy_2020#26]
Logger test seems to struggle from synchronization issues. MacOS CI build is failing because of this

**Comment by RogerQi** [comment]
It seems the issue was socket connection being blocked by the Github CI flow server. The issue should have been addressed in:

https://github.com/illini-robomaster/iRM_Autonomy_2020/commit/cef5cbec99b52bc71b930811825a91be93719677

**Comment by alvinsunyixiao** [comment]
Related PR #27 merged. Closing this.
