### ISSUE TITLE
Utilize difficulty information from DJI ROCO

### ISSUE THREAD

**Issue by alvinsunyixiao** [illini-robomaster/iRM_Autonomy_2020#34]
DJI ROCO dataset contains an optional `difficulty` field for each bounding box indicating occlusion level. This could be utilized to construct some sort of **invalid mask** to not learn super ambiguous samples.

**Comment by RogerQi** [comment]
https://github.com/illini-robomaster/iRM_Autonomy_2020/commit/faae83feea8bfb45552d016c34b89d141fa80deb

**Comment by alvinsunyixiao** [comment]
Closed by #43.

**Comment by alvinsunyixiao** [comment]
Closed by #43
